#!/bin/sh

set -x -eo pipefail

###
# Installation
###

apk add --no-cache go
apk add --no-cache curl

curl -sSLo /usr/local/bin/terraform-docs \
https://github.com/segmentio/terraform-docs/releases/download/${TERRAFORM_DOCS_VERSION}/terraform-docs-${TERRAFORM_DOCS_VERSION}-linux-amd64

ln -s /usr/local/bin/terraform-docs /usr/local/bin/terraform-docs${TERRAFORM_DOCS_VERSION}

chmod +x /usr/local/bin/terraform-docs

###
# Cleaning image
###

apk del curl go

###
# CIS Hardening
###

chmod 0600 /etc/shadow

touch /etc/login.defs
chmod 0444 /etc/login.defs